src/webadmin/routes.py
import os
import threading
import copy

from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from flask import jsonify, make_response
from flask_nav.elements import Navbar, View, Subgroup, Link, Text, Separator
from flask import request
from flask_basicauth import BasicAuth

from table.csvtable import CsvTable
from io import StringIO, TextIOWrapper

import time
import datetime
from typing import NamedTuple

from .nav import nav

from consts import MQTT_RESP_TOPIC
from consts import (
    CMD_NAME_GTWLOGERASE,
    CMD_NAME_GTWWRITE,
    CMD_NAME_MQTTWRITE,
    CMD_NAME_CNXMDBWRITE,
    TABLE_FILE_PATH
)
from consts import (
    GENERAL_INI_FILE_PATH,
    SERIAL_INI_FILE_PATH,
    CELLULAR_INI_FILE_PATH,
    MQTT_INI_FILE_PATH,
    SERIAL_INI_FILE_PATH
)

from consts import (
    TLS_CERT_CLIENT_PATH,
    TLS_KEY_CLIENT_PATH,
    TLS_CA_PATH
)

from core.utils import tail, get_file_datetime_str
from core.commands.logErase import LogEraseCommand
from core.commands.iniFileWrite import IniFileWriteCommand
from core.commands.gtwReboot import GtwRebootCommand
from core.cert_validation import validate_file

from loggers import readLogFile

frontend = Blueprint('frontend', __name__)

AnonObject = lambda **kwargs: type("Object", (), kwargs)()


def get_blueprint(basic_auth):

    def process_post(setting_provider, ini_file_path, command_name, fn=lambda sett: sett):
        if request.get_json() is not None:
            response_topic = MQTT_RESP_TOPIC.format(
                gatewayId=current_app.sets.general.gtwid)
            mqttWrite = IniFileWriteCommand(mqtt=current_app.mqtt_obj, topic=response_topic,
                                            setting_provider=setting_provider, ini_filename=ini_file_path, cmd_name=command_name, sett_strategy=fn)

            payload = {
                "settings": request.get_json()
            }

            mqttWrite.execute(command_payload=payload)

            return make_response(jsonify(True), 200)
        else:
            return make_response(jsonify(False), 400)

    @frontend.route('/')
    def index():
        modbus_status = len([x for x in current_app.slave_status_map.values(
        ) if x == True]) == len(current_app.slave_status_map.values())

        mqtt_status = current_app.mqtt_obj.is_connected if current_app.mqtt_obj is not None else False
        model = AnonObject(mqtt_info=current_app.mqtt_obj.broker_info() if current_app.mqtt_obj is not None else None,
                           mqtt_connected=mqtt_status,
                           mqtt_commmands_logtable=current_app.mqtt_commmands_logtable,
                           slave_status_map=current_app.slave_status_map,
                           modbus_status=modbus_status,
                           now=datetime.datetime.now(),
                           modbus_settings=current_app.sets.serial,
                           mbus_events=current_app.mbus_events,
                           faulted=current_app.faulted)

        return render_template('index.html', model=model)

    @frontend.route('/logs', methods=['GET', 'DELETE'])
    def logs():
        op = request.args.get('op')
        if op and op == 'delete':
            logmap = {
                'gwlog': current_app.gw_logger,
                'mqttlog': current_app.mqtt_logger,
                'mbuslog': current_app.modbus_logger,
            }
            which = request.args.get('subject')
            _clearlog(current_app.mqtt_obj,
                      current_app.sets.general.gtwid, logmap[which])
            return make_response(jsonify(True), 200)
        else:
            log_data = readLogFile(current_app.gw_logger)
            return render_template('logs.html', log_buffer=log_data)

    @frontend.route('/getlog', methods=['GET'])
    def getlog():
        logmap = {
            'gwlog': current_app.gw_logger,
            'mqttlog': current_app.mqtt_logger,
            'mbuslog': current_app.modbus_logger,
        }
        which = request.args.get('subject')

        log_data = readLogFile(logmap[which])
        return log_data

    def _clearlog(mqtt_obj, gatewayId, logger):
        response_topic = MQTT_RESP_TOPIC.format(gatewayId=gatewayId)
        cmd = LogEraseCommand(mqtt=mqtt_obj, topic=response_topic,
                              logger=logger, cmd_name=CMD_NAME_GTWLOGERASE)

        cmd.execute()

    @frontend.route('/commands', methods=['GET', 'POST'])
    @basic_auth.required
    def commands():
        return render_template('commands.html')

    def _reboot_fun(mqtt_obj, response_topic):
        cmd = GtwRebootCommand(mqtt=mqtt_obj, topic=response_topic)
        cmd.execute()

    @frontend.route('/reboot', methods=['POST'])
    # @basic_auth.required
    def reboot():
        response_topic = MQTT_RESP_TOPIC.format(
            gatewayId=current_app.sets.general.gtwid)
        thread = threading.Thread(target=_reboot_fun, args=(
            current_app.mqtt_obj, response_topic))
        thread.start()

        # cmd = GtwRebootCommand(mqtt=current_app.mqtt_obj, topic=response_topic)
        # cmd.execute()
        return make_response(jsonify(True), 200)

    @frontend.route('/general', methods=['GET', 'POST'])
    @basic_auth.required
    def general():
        if request.method == 'GET':
            return render_template('general.html',
                                   general=current_app.sets.general
                                   )
        elif request.method == 'POST':
            json_post = {}
            [json_post.update(item) for item in request.get_json()]
            current_app.config['BASIC_AUTH_USERNAME'] = json_post['adminusr']
            current_app.config['BASIC_AUTH_PASSWORD'] = json_post['adminpwd']
            return process_post(current_app.sets.general, GENERAL_INI_FILE_PATH, CMD_NAME_GTWWRITE)

    @frontend.route('/mqtt', methods=['GET', 'POST'])
    @basic_auth.required
    def mqtt():
        if request.method == 'GET':
            # Certs data should be hidden in respons
            mqtt_copy = copy.copy(current_app.sets.mqtt)

            mqtt_copy.cert_file = "*****"
            mqtt_copy.cert_file_lasttime = get_file_datetime_str(
                TLS_CERT_CLIENT_PATH)

            mqtt_copy.key_file = "*****"
            mqtt_copy.key_file_lasttime = get_file_datetime_str(
                TLS_KEY_CLIENT_PATH)

            mqtt_copy.ca_file = "*****"
            mqtt_copy.ca_file_lasttime = get_file_datetime_str(
                TLS_KEY_CLIENT_PATH)

            return render_template('mqtt.html', mqtt=mqtt_copy)
        elif request.method == 'POST':
            return process_post(current_app.sets.mqtt, MQTT_INI_FILE_PATH, CMD_NAME_MQTTWRITE)

    @frontend.route('/serial', methods=['GET', 'POST'])
    @basic_auth.required
    def serial():
        if request.method == 'GET':
            return render_template('serial.html', serial=current_app.sets.serial)
        elif request.method == 'POST':

            return process_post(current_app.sets.serial, SERIAL_INI_FILE_PATH, CMD_NAME_CNXMDBWRITE)

    @frontend.route('/table', methods=['GET', 'POST'])
    @basic_auth.required
    def table():
        if request.method == 'GET':
            with open(TABLE_FILE_PATH, 'r') as csvfile:
                return render_template('table.html', table_buffer=csvfile.read())
        elif request.method == 'POST':
            tablebuffer = request.get_json()['tablebuffer']
            f = StringIO(tablebuffer)
            c = CsvTable(f)
            (errors, table) = c.tableListValidated()
            if len(errors) > 0:
                return make_response('<br />'.join([err[0] for err in errors ]), 400)
            else:
                with open(TABLE_FILE_PATH, 'w') as csvfile:
                    csvfile.write(tablebuffer)

            return make_response(jsonify(True), 200)

    @frontend.route('/cert_upload/<file_type>', methods=['POST'])
    def cert_upload(file_type):
        file_name = None
        if request.method == 'POST':
            file_val = request.files[file_type]
            file_content = TextIOWrapper(file_val)

            cert_settings = {
                'cert': {'validations': ('-----BEGIN CERTIFICATE-----', '-----END CERTIFICATE-----'), 'filename': TLS_CERT_CLIENT_PATH},
                'ca':  {'validations': ('-----BEGIN CERTIFICATE-----', '-----END CERTIFICATE-----'), 'filename': TLS_CA_PATH},
                'key':  {'validations': ('-----BEGIN RSA PRIVATE KEY-----', '-----END RSA PRIVATE KEY-----'), 'filename': TLS_KEY_CLIENT_PATH}
            }

            if not validate_file(file_content.read(), *cert_settings[file_type]['validations']):
                return make_response("Wrong file format", 400)

            file_val.seek(0)
            file_val.save(cert_settings[file_type]['filename'])

            if file_type == 'cert':
                print(f"Setting cert_file to {file_name}")
                current_app.sets.mqtt.cert_file = cert_settings[file_type]['filename']
            elif file_type == 'key':
                print(f"Setting key_file to {file_name}")
                current_app.sets.mqtt.key_file = cert_settings[file_type]['filename']
            elif file_type == 'ca':
                print(f"Setting ca_file to {file_name}")
                current_app.sets.mqtt.ca_file = cert_settings[file_type]['filename']

            process_post(current_app.sets.mqtt,
                         MQTT_INI_FILE_PATH, CMD_NAME_MQTTWRITE)

        return make_response(jsonify(file_name), 200)

    @frontend.route('/doc')
    def doc():
        return render_template('doc.html'), 200

    @frontend.route('/logout')
    def Logout():
        return render_template('logout.html'), 401

    return frontend

src/webadmin/templates/breadcrumb.html
{% macro breadcrumb(names) %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        {% for name in names %}
        <li class="breadcrumb-item active" aria-current="page">{{name}}</li>
        {% endfor %}
    </ol>
</nav>
{% endmacro %}

src/webadmin/templates/commands.html
{%- extends "base_bootstrap.html" %}

{% from "breadcrumb.html" import breadcrumb with context %}

{% block content %}

{{ breadcrumb(['Commands']) }}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm px-4 py-4">
            <button id="gwlog" type="button" class="btn btn-primary">Clear
                gateway
                log</button>
            <button id="mqttlog" type="button" class="btn btn btn-secondary">Clear
                MQTT
                log</button>

            <button id="mbuslog" type="button" class="btn btn-success">Clear
                ModBus
                log</button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm px-4 py-4">

            <button id="gatewayReboot" type="button" class="btn btn-primary">Gateway
                reboot</button>


            <button id="mqttReboot" type="button" class="btn btn btn-secondary">Mqtt
                reboot</button>

            <button id="modbusReboot" type="button" class="btn btn-success">ModBus
                reboot</button>

        </div>

    </div>

</div>

<div id="opresult" class="alert alert-warning alert-dismissible fade" role="alert">
    <strong>Operazione eseguita
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
</div>

<!-- Modal -->
<div class="modal fade" id="waitModal" tabindex="-1" role="dialog" aaria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-body">
                <img src="static/images/spinning-wheel.gif" alt="spinning" style="height: 40px"> Rebooting ...
            </div>

        </div>
    </div>
</div>

<script>
    $(function () {

        ['gwlog', 'mqttlog', 'mbuslog'].forEach(function (value) {
            $('#' + value).click(function () {
                $.ajax({
                    url: "{{ url_for('frontend.logs') }}",
                    type: 'GET',
                    data: { op: 'delete', subject: value },
                    success: function (result) {
                        $('#opresult').addClass('show');
                    }
                });
            });
        });

        const delay = 550;
        [
            { id: '#gatewayReboot', code: 'gateway' },
            { id: '#mqttReboot', code: 'mqtt' },
            { id: '#modbusReboot', code: 'modbus' },
        ].forEach((item) => {
            $(item.id).click(function () {
                $('#waitModal').modal({ show: true });
                $.ajax({
                    url: "{{ url_for('frontend.reboot') }}",
                    type: 'POST',
                    data: { subject: item.code },
                    success: function (result) {
                        setTimeout(function () { document.location.href = "/"; }, delay);
                    },
                    error: function () {
                        setTimeout(function () { document.location.href = "/"; }, delay);
                    }
                });

            });
        });


    });
</script>


{%- endblock %}

src/webadmin/templates/general.html
{%- extends "base_bootstrap.html" %}

{% from "breadcrumb.html" import breadcrumb with context %}

{% block content %}

{{ breadcrumb(['Config', 'general']) }}

<div class="content">
  <div class="row-m">
    <form id="general_form" action="{{ url_for('frontend.general') }}" method="post">
      <div class="form-group">
        <label for="gtwid">Gateway Id</label>
        <input type="text" class="form-control validate[required]" id="gtwid" name="gtwid"
          placeholder="Enter Gateway Id" value="{{general.gtwid}}">
      </div>
      <div class="form-group">
        <label for="name">Gateway Name</label>
        <input type="text" class="form-control validate[required]" id="name" name="name"
          placeholder="Enter Gateway Name" value="{{general.name}}">
      </div>

      <div class="form-group">
        <label for="adminusr">Admin user</label>
        <input type="text" class="form-control validate[required]" id="adminusr" name="adminusr"
          placeholder="Enter Gateway admin user" value="{{general.adminusr}}">
      </div>

      <div class="form-group">
        <label for="adminpwd">Admin password</label>
        <input type="password" class="form-control validate[required]" id="adminpwd" name="adminpwd"
          placeholder="Enter Gateway admin user password" value="{{general.adminpwd}}">
      </div>

      <div class="row-m">
        <div class="col-6">
          <input type="submit" name="submit" class="btn btn-primary" value="Save" />
        </div>
      </div>

    </form>

    <div id="opresult" class="alert alert-warning alert-dismissible fade" role="alert">
      <strong>Dati salvati
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <script>
      $(document).ready(function () {
        $form = $("#general_form");

        $form.validationEngine('attach', {
          promptPosition: "topLeft",
          scroll: true, ajaxFormValidation: true,
          ajaxFormValidationMethod: 'post'
        });

        handleAjaxForm($form, function (err, resp) {
          $('#opresult').addClass('show');
        });

      });
    </script>
  </div>

</div>
{%- endblock %}

src/webadmin/templates/logout.html
{%- extends "base_bootstrap.html" %}

{% block content %}


<script>
(function() {
    window.location.href = "/";
}());
</script>
{%- endblock %}

src/webadmin/templates/logs.html
{%- extends "base_bootstrap.html" %}

{% from "breadcrumb.html" import breadcrumb with context %}

{% block content %}

{{ breadcrumb(['Logs']) }}

<ul class="nav justify-content-center">
  <li class="tab nav-item ">
    <a id="gwlog" class="nav-link active" href="#">Gateway</a>
  </li>
  <li class="tab nav-item">
    <a id="mqttlog" class="nav-link" href="#">MQTT</a>
  </li>
  <li class="tab nav-item">
    <a id="mbuslog" class="nav-link" href="#">ModBus</a>
  </li>

</ul>

<div class="content">
  {% autoescape false %}
  <textarea id="logarea" class="col-12" rows="25"  placeholder="" required>{{ log_buffer }}</textarea>
  {% endautoescape %}
</div>
<script>


  $(document).ready(function () {
    function activate(which) {
      $('a.nav-link').removeClass('active');
      $(which).addClass('active');
    }

    ['gwlog', 'mqttlog', 'mbuslog'].forEach(function (value) {
      $('#' + value).click(function () {
        activate('#' + value);
        $.ajax({
          url: "{{ url_for('frontend.getlog') }}",
          type: 'GET',
          data: { subject: value },
          success: function (result) {
            $('#logarea').val(result);
          }
        });
      });
    });

  });
</script>


{%- endblock %}

src/webadmin/templates/mqtt.html
{%- extends "base_bootstrap.html" %}
{% from "breadcrumb.html" import breadcrumb with context %}

{% block content %}

{{ breadcrumb(['Config', 'MQTT']) }}

<div id="opresult" class="alert alert-warning alert-dismissible fade" role="alert">
  <strong>Dati salvati
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
</div>

<div id='alert_placeholder'></div>

<div class="content">
  <div class="row-m">
    <form id="mqtt_form" action="{{ url_for('frontend.mqtt') }}" method="post">

      <div class="form-group">
        <label for="broker_pri">Primary Broker address</label>
        <input type="text" class="form-control validate[required]" id="broker_pri" name="broker_pri"
          placeholder="Enter primary broker address" value="{{mqtt.broker_pri}}">
      </div>

      <div class="form-group">
        <label for="broker_sec">Secondary Broker address</label>
        <input type="text" class="form-control validate[required]" id="broker_sec" name="broker_sec"
          placeholder="Enter secondary broker address" value="{{mqtt.broker_sec}}">
      </div>

      <div class="form-group">
        <label for="qos">QoS</label>
        <input type="text" class="form-control validate[required]" id="qos" name="qos" placeholder="QoS (0, 1, 2)"
          value="{{mqtt.qos}}">
      </div>

      <div class="form-group form-check">
        <div class="container-fluid">
          <input type="checkbox" class="form-check-input" id="user_auth" name="user_auth"
            {% if mqtt.user_auth.lower() == 's' %}checked{% endif %} value="S">
          <label class="form-check-label" for="user_auth">User auth</label>
        </div>
        <div class="container-fluid">
          <input type="checkbox" class="form-check-input" id="cert_auth" name="cert_auth"
            {% if mqtt.cert_auth.lower() == 's' %}checked{% endif %}>
          <label class="form-check-label" for="cert_auth">Cert auth</label>
        </div>
      </div>

      <div class="form-group" id="username_block">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter broker username"
          value="{{mqtt.username}}">
      </div>

      <div class="form-group" id="password_block">
        <label for="syspwd">Passowrd</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter broker password"
          value="{{mqtt.password}}">
      </div>

      <!-- CERTIFICATE BLOCK -->
      <div class="form-group" id="cert_file_block">
        <label for="cert">Certificate file upload</label>
        <input type="file" class="form-control" id="cert" name="cert" style="width: 30%;">
        {% if mqtt.cert_file_lasttime is not none %}
          <i class="far fa-check-square"></i> ultimo caricamento {{mqtt.cert_file_lasttime}}
        {% else %}
          <i class="far fa-square"></i> nessun file presente
        {% endif  %}
       </div>

      <div class="form-group" id="key_file_block">
        <label for="key">Key file upload</label>
        <input type="file" class="form-control" id="key" name="key" style="width: 30%;">
        {% if mqtt.key_file_lasttime is not none %}
          <i class="far fa-check-square"></i> ultimo caricamento {{mqtt.key_file_lasttime}}
        {% else %}
          <i class="far fa-square"></i> nessun file presente
        {% endif  %}
      </div>


      <div class="form-group" id="ca_file_block">
        <label for="ca">CA file upload</label>
        <input type="file" class="form-control" id="ca" name="key" style="width: 30%;">
        {% if mqtt.ca_file_lasttime is not none %}
          <i class="far fa-check-square"></i> ultimo caricamento {{mqtt.ca_file_lasttime}}
        {% else %}
          <i class="far fa-square"></i> nessun file presente
        {% endif  %}
      </div>
  </div>
  <!-- /CERTIFICATE BLOCK -->

  <div class="row-m">
    <div class="col-6">
      <input type="submit" name="submit" class="btn btn-primary" value="Save" />
    </div>
  </div>
  </form>

  <script>

    alertbox = function () { }
    alertbox.warning = function (message) {
      $('#alert_placeholder').append(`<div class="alert alert-warning" role="alert">
              <strong>${message}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>`)
    }

    function handleUserAuth() {
      let checked = $('#user_auth').is(':checked')
      if (checked) {
        $('#username_block').show();
        $('#password_block').show();
        $('#username').addClass('validate[required]');
        $('#password').addClass('validate[required]');

      } else {
        $('#username_block').hide();
        $('#password_block').hide();
        $('#username').removeClass('validate[required]');
        $('#password').removeClass('validate[required]');
      }
    }

    function handleCertAuth() {
      let checked = $('#cert_auth').is(':checked')
      if (checked) {
        $('#cert_file_block').show();
        $('#key_file_block').show();
        $('#ca_file_block').show();
      } else {
        $('#cert_file_block').hide();
        $('#key_file_block').hide();
        $('#ca_file_block').hide();
      }
    }

    $(document).ready(function () {
      $form = $("#mqtt_form");

      [
        {
          $control: $("#cert"),
          $file_input: $('#cert'),
          $textbox: $('#cert_file'),
          name: 'cert',
          url: "{{ url_for('frontend.cert_upload', file_type='cert') }}"
        },
        {
          $control: $("#key"),
          $file_input: $('#key'),
          $textbox: $('#key_file'),
          name: 'key', url: "{{ url_for('frontend.cert_upload', file_type='key') }}"
        },
        {
          $control: $("#ca"),
          $file_input: $('#ca'),
          $textbox: $('#ca_file'),
          name: 'ca', url: "{{ url_for('frontend.cert_upload', file_type='ca') }}"
        }
      ].forEach(item => {
        item.$control.change(function () {
          let formdata = new FormData();

          item.$file_input = $(`#${item.name}`);
          if (item.$file_input.prop('files').length > 0) {
            file = item.$file_input.prop('files')[0];
            formdata.append(item.name, file);
          }

          $.ajax({
            type: "POST",
            url: item.url,
            data: formdata,
            processData: false,
            contentType: false,
            success: function (data) {
              item.$textbox.val(data);
              alertbox.warning('File caricato, salvare i dati per attivarlo nella configurazione')
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) { 
              alertbox.warning('Impossibile caricare il file, controllare il formato')
            }
          });
        });
      });


      $form.validationEngine('attach', {
        promptPosition: "topLeft",
        scroll: true, ajaxFormValidation: true,
        ajaxFormValidationMethod: 'post'
      });

      handleAjaxForm($form, function (err, resp) {
        $('#opresult').addClass('show');
      });

      $('#user_auth').change(function () {
        handleUserAuth();
      });

      $('#cert_auth').change(function () {
        handleCertAuth();
      });

      handleUserAuth();
      handleCertAuth();
    });
  </script>
</div>

</div>
{%- endblock %}

src/webadmin/templates/serial.html
{%- extends "base_bootstrap.html" %}
{% from "breadcrumb.html" import breadcrumb with context %}

{% block content %}
{{ breadcrumb(['Config', 'serial']) }}

<div class="content">
  <div class="row-m">
    <form id="serial_form" action="{{ url_for('frontend.serial') }}" method="post">

      <div class="form-group">
        <label for="port">Serial port</label>
        <input type="text" class="form-control validate[required]" id="port" name="port"
          placeholder="Enter serial port device" value="{{serial.port}}" readonly >
      </div>

      <div class="form-group">
        <label for="speed">Speed</label>
        <input type="text" class="form-control validate[required]" id="speed" name="speed"
          placeholder="Enter port speed" value="{{serial.speed}}">
      </div>

      <div class="form-group">
        <label for="parity">Parity</label>
        <input type="text" class="form-control validate[required]" id="parity" name="parity"
          placeholder="Enter serial parity" value="{{serial.parity}}">
      </div>

      <div class="form-group">
        <label for="stopbit">Stop bit</label>
        <input type="text" class="form-control validate[required]" id="stopbit" name="stopbit"
          placeholder="Enter serial stopbit" value="{{serial.stopbit}}">
      </div>

      <div class="form-group">
        <label for="bitlen">Bit length</label>
        <input type="text" class="form-control validate[required]" id="bitlen" name="bitlen"
          placeholder="Enter serial bitlen" value="{{serial.bitlen}}">
      </div>

      <div class="form-group">
        <label for="master_id">Master id</label>
        <input type="text" class="form-control validate[required]" id="master_id" name="master_id"
          placeholder="Enter ModBus master id" value="{{serial.master_id}}">
      </div>

      <div class="form-group">
        <label for="polling_time">Polling time</label>
        <input type="text" class="form-control validate[required]" id="polling_time" name="polling_time"
          placeholder="Enter polling time" value="{{serial.polling_time}}">
      </div>

      <div class="form-group">
        <label for="connect_timeout">Connect timeout</label>
        <input type="text" class="form-control validate[required]" id="connect_timeout" name="connect_timeout"
          placeholder="Enter connect timeout" value="{{serial.connect_timeout}}">
      </div>

      <div class="form-group">
        <label for="retry_count">Connect retry count</label>
        <input type="text" class="form-control validate[required]" id="retry_count" name="retry_count"
          placeholder="Enter connect retry count" value="{{serial.retry_count}}">
      </div>

      <div class="row-m">
        <div class="col-6">
          <input type="submit" name="submit" class="btn btn-primary" value="Save" />
        </div>
      </div>


    </form>
    <div id="opresult" class="alert alert-warning alert-dismissible fade" role="alert">
      <strong>Dati salvati
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <script>
      $(document).ready(function () {
        $form = $("#serial_form");

        $form.validationEngine('attach', {
          promptPosition: "topLeft",
          scroll: true, ajaxFormValidation: true,
          ajaxFormValidationMethod: 'post'
        });

        handleAjaxForm($form, function (err, resp) {
          $('#opresult').addClass('show');
        });

      });
    </script>
  </div>
</div>
{%- endblock %}

src/webadmin/templates/table.html
{%- extends "base_bootstrap.html" %}
{% from "breadcrumb.html" import breadcrumb with context %}

{% block content %}
{{ breadcrumb(['ModBus/MQTT table']) }}


<div id="opresult" style="display: none;" class="alert alert-warning alert-dismissible fade" role="alert">
    <strong>Operazione eseguita
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="content">
    {% autoescape false %}
    <textarea id="tablearea" class="col-12" rows="20" placeholder="" required>{{ table_buffer }}</textarea>
    {% endautoescape %}
    
    <button id="save" type="button" class="btn btn-primary">Salva</button>
    
    <div id="operr" style="display: none;" class="alert alert-error alert-dismissible fade" role="alert">
        <strong>Errore di validazione <span id="errs"></span>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>


<script>
    $(document).ready(function () {


        $('#save').click(function () {
            const value = $('#tablearea').val();
            console.log("VALUE " + value);
            $.ajax({
                url: "{{ url_for('frontend.table') }}",
                type: 'POST',
                contentType: "application/json",
                dataType: 'json',
                data: JSON.stringify({ tablebuffer: value }),
                success: function (result) {
                    $('#opresult').show();
                    $('#opresult').addClass('show');
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    $('#operr').show();
                    $('#operr').addClass('show');
                    $('#errs').html(XMLHttpRequest.responseText);
                }
            });
        });
    });
</script>

{%- endblock %}